---
- name: Automatic low disk Remediation from Alert Manager
  hosts: all
  sources:
    - name: Listen for alerts from Alert Manager
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 8000
  rules:
    - name: LowDiskSpaceDetected
      condition: event.payload.status == "firing"
      action: 
        run_job_template:
          name: "EDA Automated Response to LowDiskSpaceDetected"
          organization: "Infrastructure"
          
